# Pass this script the path to a CSV generated by the bash script 1_... and it will print the deepest HOG for each protein on the screen
require "csv"
require "net/http"
require "json"

puts "target,hogs_with_deepest_levels"
CSV.foreach(ARGV.first, headers: true) do |row|
  print row["target"] + ","
  json = JSON.parse(Net::HTTP.get(URI("https://omabrowser.org/api/sequence/?format=json&query=" + row["peptide_sequence"])))
  hogs = json["targets"].select { |t| t["species"]["taxon_id"] == 4081 }.map { |t| t["oma_hog_id"].split(".").first }.uniq.compact

  hogs.each do |hog|
    json = JSON.parse(Net::HTTP.get(URI("https://omabrowser.org/api/hog/#{hog}/members/?format=json")))
    print(hog + "->" + json["level"] + " ")
  end

  puts
end

