# This script takes all the CSVs generated by script 1 and, selectsthe most ancient HOG for each protein
# and combines them all into one big CSV file used for plotting in script 3.
require "csv"

levels = IO.readlines("clades_hierarchy.txt").map(&:chomp)

puts "target,deepest_level,set"
Dir.glob("output/hogs/*.csv").each do |g|
  name = g.split("/").last.split(".").first

  CSV.foreach(g, headers: true) do |row|
    if row[1] and row[1] != "TIMEOUT"
      level = row[1].split(" ").map{ |h| h.split("->")[1] }.map{ |h| levels.index(h) }.min
    else
      level = levels.length - 1
    end
    puts "#{row[0]},#{level},#{name}"
  end
end
